# Dockerfile.scorer
FROM python:3.11-slim

# install libgomp for lightgbm
RUN apt-get update \
 && apt-get install -y libgomp1 \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app ./app
COPY notebooks/final_lightgbm_tuned.txt ./model/final_lightgbm_tuned.txt

WORKDIR /app/app
CMD ["python", "-u", "consumers/scorer.py"]