FROM python:3.11

WORKDIR /app

COPY requirements.txt .       
RUN pip install --no-cache-dir -r requirements.txt

COPY app/ /app/app/             

ENV PYTHONPATH=/app             

CMD ["python", "-u", "app/consumers/feature_extractor.py"]